### ISSUE TITLE
Make sure H1 markdown matches the mockups

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#111]
Was added quickly to fix for soft launch, but will need to be beautified to match Udra and Moth's mockups.

**Comment by OHaiDanny** [comment]
I think we can't use h1 since there are some hugo features (like table of conents) where it does not detect a h1 tag.

**Comment by lailleo** [comment]
We might need to make H2 match it, in that case.

**Comment by OHaiDanny** [comment]
With the recent discovery by @hintxiv, we can now use H1 with Table of Contents. I'll update the styles for it to match the mockup from frontend pins 😄
