### ISSUE TITLE
Still using `.Parent.title` instead of `.Parent.Params.job_name` in guide pages (or at least single.html)

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#117]
[pls fix or I will use another gif](https://github.com/The-Balance-FFXIV/glam/blob/4b5c9e25df94d8274e4e2100f036d653fc8ff0e9/layouts/jobs/single.html#L8)

**Comment by rexatlanti** [comment]
fixed with #123
