### ISSUE TITLE
Fix tables to match mockups from Frontend team

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#126]
Mockup is pinned in frontend thread of site channel.

**Comment by nonowazu** [comment]
It would be good to get a photo here for reference.

**Comment by OHaiDanny** [comment]
I believe the mockup is this: https://cdn.discordapp.com/attachments/882335434070433823/909613742977855538/Formatting_1.png

**Comment by OHaiDanny** [comment]
I'll work on this one :)

**Comment by OHaiDanny** [comment]
PR created!

**Comment by nonowazu** [comment]
Addressed by #151
