### ISSUE TITLE
Banners at the top of pages are still broken for some jobs

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#128]
All melee, dancer and all casters (including SMN) all are broken at the top.

![image](https://user-images.githubusercontent.com/89170008/141717115-3696d1f7-cd58-4510-a318-71f511674ccd.png)

**Comment by nonowazu** [comment]
This should be resolved, but I think this was a `balance-static` issue. Or maybe not. Either way, resolved now.
