### ISSUE TITLE
suggested vscode plugins?

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#13]
Might be useful to suggest some vscode plugins to make external dev easier to tolerate for theme dev. I found [this](https://marketplace.visualstudio.com/items?itemName=budparr.language-hugo-vscode) one, but any other suggestions are probably good ones.

**Comment by ScrubbyXIV** [comment]
There's a couple of plugins for vscode mentioned here: https://gohugo.io/tools/editors/#visual-studio-code
