### ISSUE TITLE
Match "The Balance" on top left to mocks

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#132]
![image](https://user-images.githubusercontent.com/89170008/141735138-89dc8f13-c114-4d14-b209-1796b35620df.png)

**Comment by lailleo** [comment]
![image](https://user-images.githubusercontent.com/89170008/141737944-cb2c78b7-b97c-455e-81a1-266a5efd00f4.png)

How it appears now.

**Comment by nonowazu** [comment]
We'll probably need to set either a parameter in the editor or something else to override both the title and the icon.
It's worth discussing how to work that out, but perhaps something like this?

```
headerIcon = '/assets/icon/logo.png'
headerTextImg = '/assets/icon/text.png'
```

**Comment by OHaiDanny** [comment]
Working on this...
