### ISSUE TITLE
[minor] Should make "${JOBTITLE}" link back to job landing page

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#135]
Specifically this:
<img width="742" alt="Screen Shot 2021-11-15 at 8 37 12 AM" src="https://user-images.githubusercontent.com/83298827/141800314-b4e5f6d6-95fb-4f33-ad10-447c6a7d6d7e.png">

It makes sense to me, anyway.

**Comment by OHaiDanny** [comment]
I'll take a look at this!

**Comment by nonowazu** [comment]
Addressed by #148 and #162
