### ISSUE TITLE
H3 and below (as well as body text) need more padding after line dividers

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#140]
H2 appears as such:

![image](https://user-images.githubusercontent.com/89170008/141850807-87ee5f68-8ec3-4551-9177-00fc12262f56.png)

Everything else appears as thus and should be like the H2:

![image](https://user-images.githubusercontent.com/89170008/141850846-3ff2f47e-a4a7-40a3-9c15-59b6a3f49bf5.png)

**Comment by OHaiDanny** [comment]
I noticed that all the horizontal lines <hr> don't have any styling. They usually will have a margin-bottom to push the next block of content down to create space. Let me investigate this...

**Comment by rexatlanti** [comment]
fixed with #164
