### ISSUE TITLE
Bullet points are not working

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#142]
Shows as this on theme and worked on old theme:

![image](https://user-images.githubusercontent.com/89170008/141878810-d1f89265-580d-44ee-b868-ea74ed8860e3.png)

![image](https://user-images.githubusercontent.com/89170008/141878824-d0f52e0a-d6f0-4877-a565-a8fcd2e0e57b.png)

Shows like this on page:

![image](https://user-images.githubusercontent.com/89170008/141878859-ade68caf-e14d-412b-a350-7e13fa972d2a.png)

**Comment by OHaiDanny** [comment]
PR created!
