### ISSUE TITLE
table of contents rendering/plugin?

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#15]
We'll definitely want to write something that generates (in the client or at build time) a table of contents for people to use to quickly navigate throughout the document.

I did get some feedback on suggestion (where my feedback was turning all h1/h2/etc into table of contents piece):
> I mean, what if someone wants to use an h2 and not have it become a tab

So this is something that will likely need to be considered as part of this

**Comment by sneakycrow** [comment]
I've started working on while introducing Vue.
