### ISSUE TITLE
No margin in CSS

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#155]
Set to 0, causing major issues with guide rendering:

![image](https://user-images.githubusercontent.com/89170008/141952269-77c4f2ac-97b1-4234-9f18-37e1398ef32c.png)

**Comment by OHaiDanny** [comment]
I believe @hintxiv has addressed this issue in a merged PR?

**Comment by OHaiDanny** [comment]
Checking production and I think this is fixed. I'll close the issue.
