### ISSUE TITLE
Font size increase missing from <li> and possibly other elements

### ISSUE THREAD

**Issue by TKCetonis** [The-Balance-FFXIV/glam#174]
![image](https://user-images.githubusercontent.com/89712532/142517553-2a523cb1-ea45-4aed-bd42-39f16ec1775d.png)

The font size increase looks like it may have only been applied to <p> elements, and is missing from at least li s and possibly stuff like tables. (h4 elements are now smaller than body copy too)

**Comment by rexatlanti** [comment]
Fixed with #184
