### ISSUE TITLE
Links in header nav on credits page aren't working

### ISSUE THREAD

**Issue by Nogamara** [The-Balance-FFXIV/glam#186]
https://www.thebalanceffxiv.com/pages/credits/ - all 6 links on the right side have no target

**Comment by Lunaversitay** [comment]
Assuming the credits page uses the same navbar as the entire site this "should" hopefully be fixed with the dropdown navs (https://github.com/The-Balance-FFXIV/glam/pull/190) since it'll basically force the navbar to be populated with content

**Comment by OHaiDanny** [comment]
Once #190 is in production and working, We can close this issue.
