### ISSUE TITLE
Too many characters per line on desktop (guides / articles etc)

### ISSUE THREAD

**Issue by TKCetonis** [The-Balance-FFXIV/glam#209]
The very large majority of UX / typography / writing advice I can find recommends a maximum line width of 70-80 characters, with one or two sources willing to go to 90.

The website, presently, sits around 135 on desktop. This is going to turn many people away from trying to read our content, because it will just "feel" a lot more difficult to follow than it should.

Moreover, the current situation is going to make it difficult to write guides that are readable on both desktop and mobile. Mobile screen widths vary a lot more, but personally I'm getting around 40 characters per line there.

So right now, if I have a sensible-looking 3-4 line paragraphs on desktop, it's going to be an 8-12 line wall of text on a phone. If I try to make phone paragraphs a comfy 4-6 lines, the desktop guide will be nothing but 2-line paragraphs that are super wide.

  
It may not be pragmatically feasible to get all the way down to 75 or something with the existing design, but there should be room for i.e. adding more left/right inner padding to the article container, or making the font even-bigger (on desktop only). It may be safe to trim mobile font size a little bit too.

![image](https://user-images.githubusercontent.com/89712532/142958137-7badad95-aec2-4c22-b379-0073307d414f.png)
![image](https://user-images.githubusercontent.com/89712532/142958164-10c953fc-ee0b-406c-b477-fe9c99e8affc.png)

(note that at some point a main body font size increase will demand font size increases elsewhere though)

**Comment by OHaiDanny** [comment]
The padding left and right change should be a straightforward adjustment since all our job guides are wrapped in the same CSS. Let me see what I can do
