### ISSUE TITLE
`config.toml` requires at least one `menu.header` and `menu.footer` section

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#221]
Or else the template builder gives you a bad time™.

**Comment by nonowazu** [comment]
This appears fixed in [current main](https://github.com/The-Balance-FFXIV/glam/blob/ce9147b3892d7db367d38aeea91afb007d2db5a5/exampleSite/config.toml#L18-L27). Should someone add a blurb to the `README` explaining required menu.toml items? This would completely address the issue.

**Comment by lailleo** [comment]
If someone with enough knowledge of how it works wants to do so and @ me here once it's done, I can close it, yeah.
