### ISSUE TITLE
Job icons for job pages need a consistent size

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#225]
@nonowazu suggested changing it consistently in the template.

**Comment by OHaiDanny** [comment]
@lailleo If this was referring to the White Mage job icon being immensely large in height I believe I have this addressed. I forgot to add a fixed height to contain the SVGs therefore it looked large.

A fix has already been added to production. If the paragraph above addresses the issue then I think it is good to close it.

If not, if you can give me some screenshots then I can take a closer look :)

**Comment by nonowazu** [comment]
Addressed by #229 and #230
