### ISSUE TITLE
table of contents script missing a null check

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#231]
We should check for null on [this line](https://github.com/The-Balance-FFXIV/glam/blob/68343591e14151e0a4b3aa537951606d5e6f564d/assets/js/tableOfContents.js#L35)

**Comment by hintxiv** [comment]
There is a null check

`while (sibling && sibling.tagName !== "H1")`

**Comment by nonowazu** [comment]
I'm seeing this on faq/changes/bis pages:

<img width="605" alt="Screen Shot 2021-11-29 at 8 39 37 AM" src="https://user-images.githubusercontent.com/83298827/143887604-e4f1de9b-7af1-4633-a239-f83238689b5e.png">

**Comment by hintxiv** [comment]
Oh oops
