### ISSUE TITLE
[Discussion] Not using a global in config.toml for levels

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#246]
Pros:

* Guides can show the max level they're relevant for, and can update as needed

Cons:

* Configuration in the editor for 20 x 5-6 pages
* Changing card partials to support this new frontmatter configurable

I'm of the opinion that we should punt since this only happens once every ~2 years.

**Comment by hintxiv** [comment]
Closing this since we've gone ahead with removing the max level param.
