### ISSUE TITLE
suggestion: github->discord webhooks

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#277]
If there's something pouring into a private website channel on the discord, potentially worthwhile fixes like [this](https://github.com/The-Balance-FFXIV/glam/pull/265) won't hang out for 2 months before getting merged.

**Comment by MlleCanary** [comment]
I think we have this in the Website tab now? Unless I am misunderstanding the suggestion. 

![image](https://user-images.githubusercontent.com/88956860/175435271-b4318e4b-9dc1-400a-8a6c-75717d45e7a7.png)

**Comment by lailleo** [comment]
Yep, this one was added by Hint a couple months ago? I think? There's definitely an update channel now though that didn't exist when that PR was made.

**Comment by nonowazu** [comment]
That's good. That should prevent further things from being missed then.
