### ISSUE TITLE
Images don't work for job landing pages with new multi fight tip update

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#290]
Appears like this:

![Screenshot_2022-09-02-17-12-06-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/89170008/188241630-9c302904-b644-4101-ad38-0a7f2fc664b4.jpg)

**Comment by nonowazu** [comment]
I assume it's related to my specific complaint [here](https://github.com/The-Balance-FFXIV/glam/issues/280#issuecomment-1190446784) re: the layout being hard-coded for content. That, or the editor isn't set up right on balance-static, [assuming this is the commit that added that functionality](https://github.com/The-Balance-FFXIV/balance-static/commit/ef803ab9c82d18e28db237a7a15b24e86bb44fda), @rexatlanti, can you confirm?

**Comment by rexatlanti** [comment]
That is correct. From my understanding it should work like that? Maybe I overlooked something

**Comment by nonowazu** [comment]
Since I don't have access to the admin interface (and it's relevant to balance-static specifically and not glam), this gh issue belongs in that repo.

If someone implements the structure for this fight tip stuff here and can replicate the issue, I'll look into it.

**Comment by rexatlanti** [comment]
I assume it's misconfigured somehow, yea. I'd need to check in balance static. I suppose it can be closed here

**Comment by lailleo** [comment]
Resolved.
