### ISSUE TITLE
New Extremes category is writing directly to _index with editor 

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#291]
Appears as such:

![unknown-946](https://user-images.githubusercontent.com/89170008/188241713-9faeb632-29bd-4b92-be5b-6bcef88d570b.png)

**Comment by nonowazu** [comment]
I assume that's an issue with the [balance-static admin.yml file](https://github.com/The-Balance-FFXIV/balance-static/blob/main/static/admin/config.yml), so probably not appropriate for this repo.
