### ISSUE TITLE
Preview for dark mode editor seems to be back to black text on black background

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#294]
Most recent PR merged seems to have broken this again. 

![image](https://user-images.githubusercontent.com/89170008/190885920-430de26d-e53a-47ad-bdb7-8a859cfd7cbc.png)

**Comment by nonowazu** [comment]
2 things:

1. I think that's balance-static vs glam
2. I think that's fixed in balance-static and #299 should fix the rest

I think we can close this one.
