### ISSUE TITLE
Move admin config to glam instead of static

### ISSUE THREAD

**Issue by furstblumier** [The-Balance-FFXIV/glam#296]
title. This should fix inconsistencies between static and glam

**Comment by nonowazu** [comment]
I tried this in production, but here's the steps to accomplish this:

1. Make `layouts/admin/baseof.html` - perhaps `layouts/editor/baseof.html`? I guess that depends on what you want.
2. Inside `content` (`exampleSite/content/` for here), make an `admin.md` file with the following content:

```md
---
kind: admin # alternatively, editor??
---
```

3. Make the admin/editor layout's template do the following:
    1. Detect if running in dev with `if .Site.IsServer`, and set the editor .yml file (see [here](https://www.netlifycms.org/docs/configuration-options/))
    2. Generate the main.css link (also depending if it's server or not)

**Comment by nonowazu** [comment]
#299, once merged, should fix this. Though we might want to rename some of the `package.json` scripts.
