### ISSUE TITLE
Document how to get local netlify to work

### ISSUE THREAD

**Issue by rexatlanti** [The-Balance-FFXIV/glam#297]
Currently it's completely unclear how to get netlify to work in a local dev env and we need to fix that

**Comment by hintxiv** [comment]
Fixing this through environment variables and/or a separate yarn script would be ideal if possible.

**Comment by nonowazu** [comment]
The way I've been solving it is this way:

1. Inside the repo, run `yarn start:static`
2. cd into `exampleSite` and run `../node_modules/.bin/netlify-cms-proxy-server`

It's not ideal, but it works completely for dev.
