### ISSUE TITLE
Header doesn't appear on non-front pages

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#65]
Fire up hugo locally on main and compare http://localhost:1313/ vs http://localhost:1313/jobs/healers/ vs http://localhost:1313/jobs/healers/scholar/ and notice that the header is missing.

**Comment by ductapeofdoom** [comment]
The image on http://localhost:1313/jobs/healers/scholar/ and http://localhost:1313/jobs/healers/ is using absolute positioning at 0,0 as noted in the job/header.html partial . I'm not sure the intricacies of why so I don't want to just make a change to it.

If it has to be absolute, adding a y offset for the size of the header should work.

**Comment by OHaiDanny** [comment]
I have a fix for this. I'll create a PR shortly!

**Comment by nonowazu** [comment]
@OHaiDanny – looks like that fix made the bar *visible*, but uh.. make the front page a little unusable:

![image](https://user-images.githubusercontent.com/83298827/140621435-8f74288d-a858-46e6-a16a-b8c63475e833.png)

**Comment by OHaiDanny** [comment]
Oh shoot.... let me re-check the code again. So sorry!

**Comment by OHaiDanny** [comment]
@nonowazu interesting... i've booted my local on the main branch and I can't seem to replicate the issue. Here's a screenshot of my local on the main branch. I'm wondering if this is a cache issue?

![image](https://user-images.githubusercontent.com/6521857/140622276-3acc3f75-9f95-4924-a8d5-5e8da91506d3.png)

**Comment by OHaiDanny** [comment]
I did grab the latest from the balance/glam's main branch too and it looks the same as the screenshot above 🤔

**Comment by nonowazu** [comment]
This is interesting. It's broken when I use it with the `balance-static` repo, but not with the example content directory. I'll put up a draft PR in a bit and you can pull it down to see what I'm talking about.

**Comment by OHaiDanny** [comment]
okay. I'm still unsure how the `balance-static` repo will work with the `glam` repo but I'll wait for your PR to see

**Comment by nonowazu** [comment]
Nah, there's no reason to do that. The absolute short of it is:

1. Update the `/themes/glam` git submodule
2. Change the `config.toml` to reference the glam theme
3. Fix all the issues that production has
4. Preview with production content

I had to move ~104 markdown files and change the config to make it work, so it's not for the faint of heart, hence the PR. Though I guess a branch might be appropriate.

**Comment by nonowazu** [comment]
Okay, I've created a branch on the main repo that refers to the current head of the glam repo [here](https://github.com/The-Balance-FFXIV/balance-static/tree/feat/getting-glam-orous). I'm not sorry for the pun.

**Comment by OHaiDanny** [comment]
hahaha! thanks! I'll take a look at it :)

**Comment by OHaiDanny** [comment]
@nonowazu i see what's going on. It looks like the title is called `Balance Guides`. Is this the intended title of the home page in production?

if so I'll just have to change it to reflect that in the Hugo code for the header switching.

![image](https://user-images.githubusercontent.com/6521857/140623810-a94cfcac-6350-4133-8c85-b35631b488cf.png)

**Comment by OHaiDanny** [comment]
I think i found another variable use that I can tap into that is in the config.yoml. I'm going to test this out. If it works out I'll make a PR for the `glam` repo to address this.

**Comment by OHaiDanny** [comment]
@nonowazu I think this solution should resolve it. Details inside the PR https://github.com/The-Balance-FFXIV/balance-static/pull/521

**Comment by nonowazu** [comment]
I see the PR, and I'll go ahead and merge that one. While we do this transition, I'll keep that branch up-to-date with whatever we have with glam so we can keep track of the transition.

**Comment by nonowazu** [comment]
Yes, that should fix it on the home page, but I'll wait to close this pending your potential PR for the variable in config.toml

**Comment by OHaiDanny** [comment]
Sounds good. Actually I dont think we need to change anything in the `config.toml` anymore since it was that missing _index.md file that caused Hugo to revert to using the variable in `config.toml`. 

Also from my testing it is not ideal to tap into the variable in the `config.toml` anyways since all of the pages on the website will use the same title variable.

We'll continue to monitor this then for the time being but I think we are good for now :)
