### ISSUE TITLE
Font does not match one from mock-up

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#74]
Per Moth's post, this is the font that should be used on pages:

https://fonts.google.com/specimen/Kumbh+Sans?query=kumbh

Files can be grabbed within the XD link provided.

**Comment by OHaiDanny** [comment]
I'll take this on :)

**Comment by OHaiDanny** [comment]
We can probably close this one now since Kumbh Sans has been implemented in the codebase and is showing in the soft launch build

**Comment by lailleo** [comment]
Closed, as resolved in #78
