### ISSUE TITLE
Job selector not remaining the same size, icons different sizes 

### ISSUE THREAD

**Issue by lailleo** [The-Balance-FFXIV/glam#75]
Per the front end team, this is something they'd like to see fixed before soft launch, if at all possible. Can review and change if needed after discussion. 

(Ex for icons: SCH is massive compared to WHM in our demo video)

**Comment by OHaiDanny** [comment]
I can take this on :)

**Comment by OHaiDanny** [comment]
This one has been addressed in pull request https://github.com/The-Balance-FFXIV/glam/pull/78

Maybe we can have Moth or a designer review the new sizes and if this is good we can close this task

**Comment by lailleo** [comment]
Closed, addressed in #78
