### ISSUE TITLE
theme asset svg locations aren't consistent

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#86]
For example:

```
hosaka:jobs king$ find . -iname '*.svg' -type f
./healers/sage.svg
./healers/astrologian.svg
./healers/white_mage.svg
./healers/scholar.svg
./casters/black_mage.svg
./casters/red_mage.svg
./casters/summoner.svg
./healer.svg
./melee/samurai.svg
./melee/dragoon.svg
./melee/reaper.svg
./melee/ninja.svg
./melee/monk.svg
./ranged/dancer.svg
./ranged/machinist.svg
./ranged/bard.svg
./scholar.svg
./tanks/dark_knight.svg
./tanks/warrior.svg
./tanks/paladin.svg
./tanks/gunbreaker.svg
```

`scholar.svg` seems to be at the root which works for our scholar example pages, but not for any other jobs. I think we should put it under a directory, but that means changing the templates too.

**Comment by OHaiDanny** [comment]
I think it is best to move it into a newly created scholar folder and update the pathing. That should organize everything and clean up the pathing

**Comment by ScrubbyXIV** [comment]
It looks like scholar has multiple svgs, one at the root, and one at the correct location.
```
./healers/scholar.svg
./scholar.svg
```

The files seem different, so it's not just a copied file.

`./healer.svg` also seems wrongly named, as it seems to be used for the role resources on the job pages. Should probably rename it to `./healers.svg` to make it work properly.

In addition, there's pngs in the root that are used for the job page and the role resources. 
```
$ find . -iname '*.png' -type f
./healer_ressources_background.png
./scholar_background.png
./scholar_gearing_background.png
./scholar_resources_background.png
```

**Comment by ScrubbyXIV** [comment]
@nonowazu do you know where we get the background pictures for the other jobs? The only ones currently in the repo are for scholar.

**Comment by nonowazu** [comment]
@ScrubbyXIV - I would ask Anna and Moth in the frontend or graphics threads.

**Comment by ScrubbyXIV** [comment]
@nonowazu they linked me the source, thanks. <3
Quick feedback if you got the time:
My suggestion would be to have job specific folders in static/theme-assets and have the role assets in the role folder:
```
./{role}/{job}/{job}.svg 
./{role}/{job}/{job}_background.png
./{role}/{role}.svg
...
```
Should I go with this or do you have a better idea on how to structure it?

**Comment by OHaiDanny** [comment]
I think it makes sense to me @ScrubbyXIV with what you are suggesting
