### ISSUE TITLE
editor example(s)

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#87]
- [ ] Role landing page
  - [ ] Should either hard-code or have a drop-down for the role
  - [ ] Body text might be nice, but not required
- [ ] Job landing page
  - [ ] Should probably hardcode the title (or set a param and change templates) since icons are dependent upon it

**Comment by OHaiDanny** [comment]
I'll take a stab at this one.

**Comment by OHaiDanny** [comment]
@nonowazu for the job landing page are you referring to the big "Jobs" title?

![image](https://user-images.githubusercontent.com/6521857/141405661-afa27ae8-6942-4b12-bab7-735af73d1bf0.png)
