### ISSUE TITLE
Changing asset locations breaks the role slider

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#94]
Should be a quick in the data files:
<img width="1627" alt="Screen Shot 2021-11-12 at 9 42 31 AM" src="https://user-images.githubusercontent.com/83298827/141493786-48f66a31-dd4e-4664-b08f-41965895b866.png">

**Comment by ScrubbyXIV** [comment]
Ye, should be. That's something I only realised this morning and should've mentioned in the other PR. I'll work on the fix now.

**Comment by nonowazu** [comment]
Fixed by #96
