### ISSUE TITLE
Meta box tab contents are strange

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#95]
<img width="1629" alt="Screen Shot 2021-11-12 at 9 43 43 AM" src="https://user-images.githubusercontent.com/83298827/141493998-2f0fcb80-1ef3-466f-abfb-b54e7da11897.png">

**Comment by ScrubbyXIV** [comment]
the changelog also looks a bit weird 
![image](https://user-images.githubusercontent.com/65615038/141518775-bd2bc939-b69e-44e9-b905-43197adb73b2.png)
Will try and check how to fix it
