### ISSUE TITLE
Remove "job resources" from job landing page template

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#97]
Since it's hardcoded and not functional, it's probably weird for a public launch:
<img width="2048" alt="Screen Shot 2021-11-12 at 12 50 03 PM" src="https://user-images.githubusercontent.com/83298827/141519500-0f9d2e20-4966-4d25-95e5-3fd0345be353.png">
>

**Comment by ScrubbyXIV** [comment]
I assume you mean role resources then according to the screenshot.
