### ISSUE TITLE
Fix up styling

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#98]
As of right now, we have to have a `role` field in `/content/jobs/${role}/_index.md`, but there's an issue:

* Setting it to `role: tank`:
<img width="866" alt="Screen Shot 2021-11-12 at 12 52 51 PM" src="https://user-images.githubusercontent.com/83298827/141519864-962cedcf-0cb4-48a4-bcb8-84d01e484728.png">
*  Setting it to `role: tanks`:
<img width="827" alt="Screen Shot 2021-11-12 at 12 53 15 PM" src="https://user-images.githubusercontent.com/83298827/141519905-f2ae6f34-0c01-4ac2-b420-dee3cee71117.png">

With `tank` (singular), icon and branding is missing; with `tanks` (plural), icon/branding works but the "stripe" on the left side is missing.

**Comment by ScrubbyXIV** [comment]
@nonowazu We get the assets by role, so if we go with the singular naming for it, we'll have to adjust the theme asset names.
The stripe is probably just a change in the main.css and the tailwind.config.js
Btw: Which role names will we use? In the css I found references to "dps" as a role, which I do not think is consistent with our current implementation.

**Comment by nonowazu** [comment]
@ScrubbyXIV – I think some of this is in flux, but I'm okay with with whatever the devs in the thread choose (though I'd personally lean towards singular naming where we can).

In terms of "dps" as a role, I *think* some of the theming is tied up in things like `jobs/casters/black-mage_background_banner.png` or some such, so we might as well make allowances for multiple role(s) with the same style if that's a hard blocker.

**Comment by ScrubbyXIV** [comment]
I'd have suggested to use plural for roles and just split/duplicate the styling from "dps" to "casters", "melee" and "ranged"

**Comment by nonowazu** [comment]
Then let's go with that – make it so.
